Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -22,7 +22,7 @@ jobs:
       uses: aquasecurity/trivy-action@master
       with:
         scan-type: 'fs'
-        # ignore-unfixed: true
+        ignore-unfixed: true
         format: 'sarif'
         output: 'trivy-results.sarif'
 
@@ -31,7 +31,7 @@ jobs:
       uses: actions/upload-artifact@v3
       with:
         name: trivy-output
-        path: trivy-results.sarif
+        path: 'trivy-results.sarif'
         
 # Configuring credentials for github actions
     - name: Configure AWS credentials
@@ -61,35 +61,36 @@ jobs:
       run: terraform validate -no-color
 
 # Generates an execution plan for Terraform
-    # - name: Terraform Plan
-    #   id: plan
-    #   # if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
-    #   run: |
-    #     terraform plan -no-color -input=false \
-    #     -out=tfplan
-    #   continue-on-error: true
-
     - name: Terraform Plan
-      id: tf-plan
+      id: plan
+      # if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
       run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+        terraform plan -no-color -input=false \
+        -out tf.plan
+        terraform show -no-color tf.plan > tfplan.txt
+      continue-on-error: true
 
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+    # - name: Terraform Plan
+    #   id: tf-plan
+    #   run: |
+    #     export exitcode=0
+    #     terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+    #     echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
         
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
+    #     if [ $exitcode -eq 1 ]; then
+    #       echo Terraform Plan Failed!
+    #       exit 1
+    #     else 
+    #       exit 0
+    #     fi
       
   # Save plan to artifacts
     - name: Upload the terraform plan output
       uses: actions/upload-artifact@v4
       with:
         name: tf-plan
-        path: tfplan
+        path: tfplan.txt
 
   # tfsec stage to check 
     - name: tfsec
